# Generated by Django 4.2.29 on 2026-03-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_generation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='limit_reached',
            field=models.BooleanField(default=False),
        ),
    ]
