# Generated by Django 4.2.29 on 2026-03-24 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_last_generation_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
