# Generated by Django 4.2.29 on 2026-03-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='content_type',
            field=models.CharField(choices=[('news', 'News'), ('social', 'Social'), ('headline', 'Headline')], max_length=20),
        ),
    ]
